---
- name: Configure Celery systemd service unit
  template: src=celery.service.j2 dest="/etc/systemd/system/{{item.name}}.service"
  notify: restart celery service
  with_items: "{{celery_services}}"
