---
- name: Ensure Celery Env Dir exists
  file:
    path: "{{celery_env_dir}}"
    state: directory
    owner: "{{celery_user}}"
    group: "{{celery_user}}"
    mode: 0755

- name: Ensure Celery Log Dir exists
  file:
    path: "{{celery_log_dir}}"
    state: directory
    owner: "{{celery_user}}"
    group: "{{celery_user}}"
    mode: 0755

- name: Ensure Celery Run Dir exists
  file:
    path: "{{celery_run_dir}}"
    state: directory
    owner: "{{celery_user}}"
    group: "{{celery_user}}"
    mode: 0755

- name: Ensure Celery Run Dirs persists after reboot
  template:
    src: celery_tmpfiles.j2
    dest: /etc/tmpfiles.d/celery.conf
    owner: root
    group: root
    mode: 0644
