---
- name: "start celery service"
  systemd:
    name: "{{item.name}}.service"
    state: started
    daemon_reload: yes
  with_items: "{{celery_services}}"

- name: "restart celery service"
  systemd:
    name: "{{item.name}}.service"
    state: restarted
    daemon_reload: yes
  with_items: "{{celery_services}}"
