---
- name: "start celery services"
  systemd:
    name: "{{item.name}}.service"
    state: started
    enabled: "{{item.enable|default('no')}}"
  with_items: "{{celery_services}}"
  when: celery_services | length > 0
  listen: "start application"

- name: "restart celery services"
  systemd:
    name: "{{item.name}}.service"
    state: restarted
    enabled: "{{item.enable|default('no')}}"
  with_items: "{{celery_services}}"
  when: celery_services | length > 0
  listen: "restart application"

- name: "stop celery services"
  systemd:
    name: "{{item.name}}.service"
    state: stopped
  with_items: "{{celery_services}}"
  when: celery_services | length > 0
  listen: "stop application"
